# Generated by Django 3.1.1 on 2020-09-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkInfo',
            fields=[
                ('homeworkId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=64)),
                ('topicName', models.CharField(max_length=64)),
                ('difficulty', models.CharField(max_length=16)),
                ('times', models.IntegerField(default=1)),
                ('comment', models.TextField()),
                ('recording', models.TextField()),
                ('chineseIssue', models.TextField(default='')),
                ('worldIssue', models.TextField(default='')),
                ('delStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('QQ', models.CharField(max_length=16)),
                ('dreamCompany', models.CharField(max_length=32)),
                ('language', models.CharField(max_length=16)),
                ('registerTime', models.DateTimeField()),
                ('delStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
